version: '3.8'

networks:
  it-mo:

services:

  backend:
    build:
      context: ./
      dockerfile: ./back/Dockerfile
    networks:
      - it-mo
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: container-registry.oracle.com/database/free:latest
    environment:
      ORACLE_PWD: password
      ORACLE_SID: FREE
      ORACLE_CHARACTERSET: AL32UTF8
    networks:
      - it-mo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "sqlplus", "-s", "sys/password@FREE as sysdba", "SELECT 1 FROM dual"]
      interval: 10s
      timeout: 5s
      retries: 20

  front:
    build:
      context: ./
      dockerfile: ./front/Dockerfile
    ports:
      - "80:80"
    networks:
      - it-mo
    depends_on:
      - backend