section .data
    %include "colon.inc" 


colon "alcohol", first 
db "not good", 0 

colon "cigaretes", second 
db "not cool", 0

colon "vapes are great?", third 
db "they are unhealthy", 0

colon "sports", fourth 
db "dangerous", 0

colon "PSZH", fifth 
db "very_loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong_nagging", 0

colon `\n`, sixth 
db "this is a newline key", 0

colon ` `, seventh 
db 'this is an empty key', 0


colon `\t`, eighth 
db 'this is a tabulation key', 0




   




